name: lorem_picsum
description: Dart client for Lorem Picsum, the Lorem Ipsum for photos
version: 0.0.1
repository: https://github.com/rmRizki/lorem_picsum

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0