name: lorem_picsum
description: Dart client for Lorem Picsum, the Lorem Ipsum for photos
version: 0.0.1+1
repository: https://github.com/rmRizki/lorem_picsum

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.0